import Head from 'next/head'
import Header from '../components/header'
import Hero from '../components/hero'

export default function Home() {
  return (
    <div className="bg-[#0b0c10] text-[#C5C6C7] h-screen">
      <Head>
        <title>Alberto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main>
        <Header/>

        {/* Hero */}
        <section id="hero">
          {/* <Hero/> */}
        </section>

      </main>
    </div>
  )
}
